aws:
  stateTableName: "ingestionTableTest"
  inboundStream: "trade-matching-ingress-us-east-1-kinesis-stream"
  outboundStream: "trade-matching-core-us-east-1-kinesis-stream"
  nackStream: ""
  region: "us-east-1"
# log level values: trace, debug, info, warn, error, fatal or off